language: node_js
node_js:
- '8'
script: npm run ci
deploy:
  matrix:
  - provider: npm
    email: lucian.buzzo@gmail.com
    api_key:
      secure: KR9QNi0hODdWGpNkz0lj+QgSEw5g1h/P1HEK4CRbhYnK4dD3RQGTUGWUzqKQlKGcg/DGrTtNtiaVL08tfveJM6wd1jSr1w22ymr3vfJq4SQAy4XYT6m0FzhrYOl9WngrtKQP9KgzAUfMaqPbpE5Lm8P32fBgCYVOuQDTOc6QLMqNngGpQp4Zknh7a1tMg/fRvFlBF9/rFYolHiApQYdYmOnGg6T6r8uNOyhNMsuQl0VuZtoRzXJuipC5mItLbfsVrsgEeb9KzM2KXU7xCeig9w5Y8QidORUgh1bMS58C9KXsNK2TFPCQE9NhcZl5xTvY2uAAwDaVkbdPQBXk+RL2KOglFW9K6MkbwxTaVXRz/AcT35bfQvEMNtmS6JqDFNQwtLe+xrZDiPw7jkYPRie69KJFwmFFcTV43Gsv4TusB1DjtGpSyhxZCDQVKxpq/EdJO2iCccTlae7Bgw/V5QhowsDyIyOeGBpgsGnin37pVXxuGwEBAD1s3/327v6WUQapMkaXDW/8NbMfnF7O9Q2Nq9TiLLqEs/AB9dZTF7qgFUrS2sDAyNzO2ZKwQkToXXnJvTOfECayX7Xc70kC4D7siu8kIAIichHB9Z/AeGNRYO/tV+yj4zMjv6kYf83VDjN9H8WRAP194aYd4gKuA5AzbWmFACEzVHaos9rITKrM4U0=
    on:
      tags: true
      repo: LucianBuzzo/icecave
