language: node_js
node_js:
- '8'
script: npm run ci
deploy:
  matrix:
  - provider: npm
    email: lucian.buzzo@gmail.com
    api_key:
      secure: OfkgoMs9mr/OqGiuA2/gkX/6Kre1ciuaHDctM/fslAGUX8uoPHJSI8ZQA6i47eon/gkzYL/4mmICzKP/EyezUizuKPskfwn7rO3WXF6wcBb0ndS/c1MNAPeyttgc0HVuSi8Qs6lySma60lbaJcTlNfr69tI1qI3YCE1u2MGZVJQ7TIu9nlMq66FRem/DoDqHszWSP1vlz1eEWAMcYZPTOjHKDLWg9olo2vv6a2iqfur95B8SOOBxfqymoi7szPrYm2QiWl9S1TgJ6XgwUPqvaSbFOeYFgX0bWe9I89GEWnhmhDwqR7wlkPB8GrgAeEe6R293B3sWD4kMMop4kkLEtJTsIeti4MRDiygCxofpAMrPdo82HHnjjrsw5BZ35HF5fHNW/E9iYvengjVk3hijYUL32tVTTh2unNVy6SHXMudEh4d0c4eI/cjs/IExNMGYYQ0l31OgX3PXkeCCD9tauEartw5IZBy7A2wF04u0Ta6KpDnUpUbDmSVWDiPmDTbdzS7jTXjutnfldddhjAa8YLj/NAmYj1oMa4Hkb1RLtJMYAaTYGJUTsRahm/9jCdkpipvYdNwroulUmBbL54a4U7tal28X8X51aN3fOmAFY20EVxSU3a8haqd9wXX7BDEAoOdBaQa1N9mtGTF8AC9q+ofZYipdUDSNQ6FNhRsayH8=
    on:
      tags: true
      repo: LucianBuzzo/dungeoneer
  api_key:
    secure: cpVNzYyvIW9km0F6VuEz0LrCxlnlGrrcEWMUeLvpXhgQdCM9CsJh4I0osynqnJlTBBBaxXASb7NGRGBbDe+8/38jYFxSpAho1tUoh9Lwb3xfNAu/IFC0nmaZmfU2Q+gXcqhoM13uEnXs3O3Emt/Bz/vTRZnebT4eTCM73o58xEPcE7lC4lXRJPOi0DkX1/SLgW/aqbDjurbmeKA1Tjk0doYoV+AO3rG+ZUzj+BZjb9sDL1Il7U6Iv1errDd6egunqYJD908VEJ3NCXaN9CiOvtufTs916Icl3AdjihYzcmJxo7NZ7Cby1cyNA61hqkEaFpg9bFOg7MHzIx0db7RInmNxF5nS2s9boXYyRH1oTYdsCOJLAShraojAwTyWnBBH9W7cLUk1ZynAJYyyK6yJzOsOUD/J1VPSLhCMq1L28arpRFclI7wPpIkcOj86+TLj7YcfwpqQNaFV48z0hYELgHHdDxPSnByb8clI/J4OK2LxuY2TuO0zjPWdhSIYk4lqmKFf2M6TBQoEv9uzq2ZBawh4WmAOrQqw8h/KuE5Fcx9NmkLGsgbi652tvBg+9UqETYDFib/JXSm2JSoqluOfmKNwsV0KMvNM7dYvjir0YlHhF+Brj2pkPO18EJDBGs0Gk8ra5g/bwZ+fRVN5hYnH3AJ6Xh5cuCjpnGtFexA67XQ=
