language: node_js
node_js:
- '8'
script: npm run ci
deploy:
  - provider: npm
    email: lucian.buzzo@gmail.com
    api_key:
      secure: cpVNzYyvIW9km0F6VuEz0LrCxlnlGrrcEWMUeLvpXhgQdCM9CsJh4I0osynqnJlTBBBaxXASb7NGRGBbDe+8/38jYFxSpAho1tUoh9Lwb3xfNAu/IFC0nmaZmfU2Q+gXcqhoM13uEnXs3O3Emt/Bz/vTRZnebT4eTCM73o58xEPcE7lC4lXRJPOi0DkX1/SLgW/aqbDjurbmeKA1Tjk0doYoV+AO3rG+ZUzj+BZjb9sDL1Il7U6Iv1errDd6egunqYJD908VEJ3NCXaN9CiOvtufTs916Icl3AdjihYzcmJxo7NZ7Cby1cyNA61hqkEaFpg9bFOg7MHzIx0db7RInmNxF5nS2s9boXYyRH1oTYdsCOJLAShraojAwTyWnBBH9W7cLUk1ZynAJYyyK6yJzOsOUD/J1VPSLhCMq1L28arpRFclI7wPpIkcOj86+TLj7YcfwpqQNaFV48z0hYELgHHdDxPSnByb8clI/J4OK2LxuY2TuO0zjPWdhSIYk4lqmKFf2M6TBQoEv9uzq2ZBawh4WmAOrQqw8h/KuE5Fcx9NmkLGsgbi652tvBg+9UqETYDFib/JXSm2JSoqluOfmKNwsV0KMvNM7dYvjir0YlHhF+Brj2pkPO18EJDBGs0Gk8ra5g/bwZ+fRVN5hYnH3AJ6Xh5cuCjpnGtFexA67XQ=
    on:
      tags: true
      repo: LucianBuzzo/IceCave-DB
